//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz02.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PV_Quiz02Entities : DbContext
    {
        public PV_Quiz02Entities()
            : base("name=PV_Quiz02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spConsultarTelefonoPorId_Result> spConsultarTelefonoPorId(Nullable<int> id_Telefono)
        {
            var id_TelefonoParameter = id_Telefono.HasValue ?
                new ObjectParameter("id_Telefono", id_Telefono) :
                new ObjectParameter("id_Telefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTelefonoPorId_Result>("spConsultarTelefonoPorId", id_TelefonoParameter);
        }
    
        public virtual ObjectResult<spConsultarTelefonos_Result> spConsultarTelefonos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTelefonos_Result>("spConsultarTelefonos");
        }
    
        public virtual int spCrearTelefono(string marca, string nombre, Nullable<int> anhoFabricacion, Nullable<System.DateTime> fechaLanzamiento, Nullable<int> precio)
        {
            var marcaParameter = marca != null ?
                new ObjectParameter("marca", marca) :
                new ObjectParameter("marca", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var anhoFabricacionParameter = anhoFabricacion.HasValue ?
                new ObjectParameter("anhoFabricacion", anhoFabricacion) :
                new ObjectParameter("anhoFabricacion", typeof(int));
    
            var fechaLanzamientoParameter = fechaLanzamiento.HasValue ?
                new ObjectParameter("fechaLanzamiento", fechaLanzamiento) :
                new ObjectParameter("fechaLanzamiento", typeof(System.DateTime));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearTelefono", marcaParameter, nombreParameter, anhoFabricacionParameter, fechaLanzamientoParameter, precioParameter);
        }
    
        public virtual int spEditarTelefono(Nullable<int> id_Telefono, string marca, string nombre, Nullable<int> anhoFabricacion, Nullable<System.DateTime> fechaLanzamiento, Nullable<int> precio)
        {
            var id_TelefonoParameter = id_Telefono.HasValue ?
                new ObjectParameter("id_Telefono", id_Telefono) :
                new ObjectParameter("id_Telefono", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("marca", marca) :
                new ObjectParameter("marca", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var anhoFabricacionParameter = anhoFabricacion.HasValue ?
                new ObjectParameter("anhoFabricacion", anhoFabricacion) :
                new ObjectParameter("anhoFabricacion", typeof(int));
    
            var fechaLanzamientoParameter = fechaLanzamiento.HasValue ?
                new ObjectParameter("fechaLanzamiento", fechaLanzamiento) :
                new ObjectParameter("fechaLanzamiento", typeof(System.DateTime));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditarTelefono", id_TelefonoParameter, marcaParameter, nombreParameter, anhoFabricacionParameter, fechaLanzamientoParameter, precioParameter);
        }
    
        public virtual int spEliminarTelefono(Nullable<int> id_Telefono)
        {
            var id_TelefonoParameter = id_Telefono.HasValue ?
                new ObjectParameter("id_Telefono", id_Telefono) :
                new ObjectParameter("id_Telefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarTelefono", id_TelefonoParameter);
        }
    }
}
